name: Green Home and Body
favicon: null
layout_spectrum: 0.1622585488948971
typography_spectrum: 0.8480355327483267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010403'
    - '#7ac5e4'
    - '#2d4747'
    - '#b78153'
    - '#8a5629'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
