name: Green Home and Body
favicon: null
layout_spectrum: 0.99394
typography_spectrum: 0.8480355327483267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#485450'
    - '#feddb4'
    - '#b96e4f'
    - '#e9af8a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
