name: Green Home and Body
favicon: null
layout_spectrum: 0.1622585488948971
typography_spectrum: 0.8480355327483267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.95966836810112
  lightness: 0.026172352489084005
  saturation: 0.4504871640820056
  rhythmicContrast: 0.7238961094990373
purpose: []
