name: Green Home and Body
favicon: null
layout_spectrum: 0.01385
typography_spectrum: 0.8480355327483267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2d68c'
    - '#82a28d'
    - '#056639'
    - '#628e3f'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
